/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.1.1-3-gfcbd9ec248-20220911"
#endif /* AVUTIL_FFVERSION_H */
